export const LOCATORS: Record<string, string> = {
  book: "book",
  "bk.": "book",
  "bks.": "book",
  chapter: "chapter",
  "chap.": "chapter",
  "chaps.": "chapter",
  column: "column",
  "col.": "column",
  "cols.": "column",
  figure: "figure",
  "fig.": "figure",
  "figs.": "figure",
  folio: "folio",
  "fol.": "folio",
  "fols.": "folio",
  number: "number",
  "no.": "number",
  "nos.": "number",
  line: "line",
  "l.": "line",
  "ll.": "line",
  note: "note",
  "n.": "note",
  "nn.": "note",
  opus: "opus",
  "op.": "opus",
  "opp.": "opus",
  page: "page",
  "p.": "page",
  "pp.": "page",
  paragraph: "paragraph",
  "para.": "paragraph",
  "paras.": "paragraph",
  part: "part",
  "pt.": "part",
  "pts.": "part",
  section: "section",
  "sec.": "section",
  "secs.": "section",
  "sub verbo": "sub verbo",
  "s.v.": "sub verbo",
  "s.vv.": "sub verbo",
  verse: "verse",
  "v.": "verse",
  "vv.": "verse",
  volume: "volume",
  "vol.": "volume",
  "vols.": "volume",
  "¶": "paragraph",
  "¶¶": "paragraph",
  "§": "section",
  "§§": "section",
};
